# Generated by Django 5.0.3 on 2024-11-18 01:27

import computed_property.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'lessons_times',
            },
        ),
        migrations.CreateModel(
            name='TTLesson',
            fields=[
                ('tt_lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_name', models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], max_length=3)),
                ('week_type', models.CharField(choices=[('EV', 'Четная неделя'), ('NE', 'Нечетная неделя'), ('CW', 'Зачетная неделя'), ('EX', 'Экзаменационная неделя')], max_length=2)),
            ],
            options={
                'db_table': 'tt_lessons',
            },
        ),
    ]
