# Generated by Django 5.0.3 on 2024-11-18 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_initial'),
        ('timetable', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lessontime',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='check_start_time'),
        ),
        migrations.AddConstraint(
            model_name='lessontime',
            constraint=models.UniqueConstraint(fields=('start_time', 'end_time'), name='lesson_time_start_time_end_time_unique'),
        ),
        migrations.AddField(
            model_name='ttlesson',
            name='classroom_id',
            field=models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.PROTECT, to='timetable.classroom'),
        ),
        migrations.AddField(
            model_name='ttlesson',
            name='curriculum_lesson_id',
            field=models.ForeignKey(db_column='curriculum_lesson_id', on_delete=django.db.models.deletion.PROTECT, to='curriculum.curriculumlesson'),
        ),
        migrations.AddField(
            model_name='ttlesson',
            name='lesson_time_id',
            field=models.ForeignKey(db_column='lesson_time_id', on_delete=django.db.models.deletion.PROTECT, to='timetable.lessontime'),
        ),
        migrations.AddConstraint(
            model_name='ttlesson',
            constraint=models.UniqueConstraint(fields=('date', 'lesson_time_id', 'curriculum_lesson_id'), name='tt_lesson_date_time_curriculum_lesson_unique'),
        ),
    ]
