# Generated by Django 5.0.3 on 2024-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_squashed_0016_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ttlesson',
            name='tt_lesson_day_week_time_curriculum_les_unique',
        ),
        migrations.AddConstraint(
            model_name='ttlesson',
            constraint=models.UniqueConstraint(fields=('date', 'lesson_time_id', 'curriculum_lesson_id'), name='tt_lesson_date_time_curriculum_lesson_unique'),
        ),
    ]
