# Generated by Django 5.0.3 on 2024-11-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'curriculums',
            },
        ),
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('curriculum_lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_type', models.CharField(choices=[('PRA', 'Практика'), ('LEC', 'Лекция'), ('LAB', 'Лабораторная работа'), ('CRD', 'Зачет'), ('EXM', 'Экзамен')], max_length=3)),
                ('duration', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'curriculum_lessons',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'disciplines',
            },
        ),
    ]
