# Generated by Django 5.0.3 on 2024-11-18 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='group_semester_id',
            field=models.ForeignKey(db_column='group_semester_id', on_delete=django.db.models.deletion.PROTECT, to='group.groupsemester'),
        ),
        migrations.AddField(
            model_name='curriculumlesson',
            name='curriculum_id',
            field=models.ForeignKey(db_column='curriculum_id', on_delete=django.db.models.deletion.PROTECT, to='curriculum.curriculum'),
        ),
    ]
