# Generated by Django 5.0.3 on 2024-11-18 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumlesson',
            name='tutor_id',
            field=models.ForeignKey(db_column='tutor_id', on_delete=django.db.models.deletion.PROTECT, to='user.tutor'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='discipline_id',
            field=models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.PROTECT, to='curriculum.discipline'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlesson',
            constraint=models.CheckConstraint(check=models.Q(('lesson_type__in', ['PRA', 'LEC', 'LAB', 'CRD', 'EXM'])), name='curriculum_curriculumlesson_correct_lesson_type'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlesson',
            constraint=models.CheckConstraint(check=models.Q(('duration__gte', 0)), name='curriculum_curriculumlesson_duration_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlesson',
            constraint=models.UniqueConstraint(fields=('curriculum_id', 'tutor_id', 'lesson_type'), name='curriculum_lessons_curriculum_tutor_les_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('discipline_id', 'group_semester_id'), name='discipline_group_sem_unique'),
        ),
    ]
