# Generated by Django 5.0.3 on 2024-11-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('group_member_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.CreateModel(
            name='GroupSemester',
            fields=[
                ('group_semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_num', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'group_semesters',
            },
        ),
    ]
