# Generated by Django 5.0.3 on 2024-11-18 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='user.student'),
        ),
        migrations.AddField(
            model_name='groupsemester',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.PROTECT, to='group.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group_semester_id',
            field=models.ForeignKey(db_column='group_semester_id', on_delete=django.db.models.deletion.PROTECT, to='group.groupsemester'),
        ),
        migrations.AddConstraint(
            model_name='groupsemester',
            constraint=models.CheckConstraint(check=models.Q(('semester_num__lte', 10)), name='group_groupsemester_semester_num_lte_10'),
        ),
        migrations.AddConstraint(
            model_name='groupsemester',
            constraint=models.UniqueConstraint(fields=('group_id', 'semester_num'), name='group_semester_num_unique'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group_semester_id', 'student_id'), name='group_members_group_semester_student_unique'),
        ),
    ]
