# Generated by Django 4.2.6 on 2023-12-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('coefficient_id', models.AutoField(primary_key=True, serialize=False)),
                ('coef_num', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'coefficient',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'curriculum',
            },
        ),
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('curriculum_lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_type', models.PositiveSmallIntegerField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.curriculum')),
            ],
            options={
                'db_table': 'curriculum_Lesson',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'lessons_time',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='TTLesson',
            fields=[
                ('tt_lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_name', models.PositiveSmallIntegerField()),
                ('week_type', models.PositiveSmallIntegerField()),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.classroom')),
                ('curriculum_lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.curriculumlesson')),
                ('lessons_time_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.lessontime')),
            ],
            options={
                'db_table': 'tt_lesson',
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.student')),
                ('tt_lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.ttlesson')),
            ],
            options={
                'db_table': 'students_progress',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_present', models.BooleanField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.student')),
                ('tt_lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.ttlesson')),
            ],
            options={
                'db_table': 'students_attendance',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('hw_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2048)),
                ('hw_type', models.PositiveSmallIntegerField()),
                ('day_due', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_due', to='polls.ttlesson')),
                ('day_given', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_given', to='polls.ttlesson')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.student')),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='GroupSemester',
            fields=[
                ('group_semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_num', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.group')),
            ],
            options={
                'db_table': 'group_semester',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('group_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_semesters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.groupsemester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.student')),
            ],
            options={
                'db_table': 'group_member',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('scale_5', models.PositiveSmallIntegerField()),
                ('scale_word', models.CharField(max_length=32)),
                ('scale_100', models.PositiveSmallIntegerField()),
                ('scale_letter', models.CharField(max_length=1)),
                ('coef_num', models.PositiveSmallIntegerField()),
                ('coef_description', models.CharField(max_length=64)),
                ('coefficient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.coefficient')),
                ('progress_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.studentprogress')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('final_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_final', models.BooleanField()),
                ('scale_5', models.PositiveSmallIntegerField()),
                ('scale_100', models.PositiveSmallIntegerField()),
                ('scale_letter', models.CharField(max_length=1)),
                ('scale_word', models.CharField(max_length=128)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.curriculum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.student')),
            ],
            options={
                'db_table': 'finalGrade',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('file', models.BinaryField()),
                ('hw_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.homework')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.AddField(
            model_name='curriculumlesson',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.tutor'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.discipline'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='group_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.groupsemester'),
        ),
    ]
