# Generated by Django 4.2.6 on 2023-12-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_group_groupsemester_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsemester',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.PROTECT, to='polls.group'),
        ),
    ]
