# Generated by Django 4.2.6 on 2023-12-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_groupsemester_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='discipline',
            field=models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.PROTECT, to='polls.discipline'),
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='discipline',
            new_name='discipline_id',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='group_semester',
            field=models.ForeignKey(db_column='group_semester_id', on_delete=django.db.models.deletion.PROTECT, to='polls.groupsemester'),
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='group_semester',
            new_name='group_semester_id',
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='curriculum',
            field=models.ForeignKey(db_column='curriculum_id', on_delete=django.db.models.deletion.PROTECT, to='polls.curriculum'),
        ),
        migrations.RenameField(
            model_name='curriculumlesson',
            old_name='curriculum',
            new_name='curriculum_id',
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='tutor',
            field=models.ForeignKey(db_column='tutor_id', on_delete=django.db.models.deletion.PROTECT, to='polls.tutor'),
        ),
        migrations.RenameField(
            model_name='curriculumlesson',
            old_name='tutor',
            new_name='tutor_id',
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='curriculum',
            field=models.ForeignKey(db_column='curriculum_id', on_delete=django.db.models.deletion.PROTECT, to='polls.curriculum'),
        ),
        migrations.RenameField(
            model_name='finalgrade',
            old_name='curriculum',
            new_name='curriculum_id',
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='polls.student'),
        ),
        migrations.RenameField(
            model_name='finalgrade',
            old_name='student',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='polls.student'),
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='student',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='file',
            name='hw_id',
            field=models.ForeignKey(db_column='hw_id', on_delete=django.db.models.deletion.PROTECT, to='polls.homework'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='coefficient_id',
            field=models.ForeignKey(db_column='coefficient_id', on_delete=django.db.models.deletion.PROTECT, to='polls.coefficient'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='progress_id',
            field=models.ForeignKey(db_column='progress_id', on_delete=django.db.models.deletion.PROTECT, to='polls.studentprogress'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_semesters',
            field=models.ForeignKey(db_column='group_semester_id', on_delete=django.db.models.deletion.PROTECT, to='polls.groupsemester'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='day_due',
            field=models.ForeignKey(db_column='day_due', on_delete=django.db.models.deletion.PROTECT, related_name='day_due', to='polls.ttlesson'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='day_given',
            field=models.ForeignKey(db_column='day_given', on_delete=django.db.models.deletion.PROTECT, related_name='day_given', to='polls.ttlesson'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='polls.student'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='polls.student'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='tt_lesson_id',
            field=models.ForeignKey(db_column='tt_lesson_id', on_delete=django.db.models.deletion.PROTECT, to='polls.ttlesson'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='polls.student'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='tt_lesson_id',
            field=models.ForeignKey(db_column='tt_lesson_id', on_delete=django.db.models.deletion.PROTECT, to='polls.ttlesson'),
        ),
        migrations.AlterField(
            model_name='ttlesson',
            name='classroom_id',
            field=models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.PROTECT, to='polls.classroom'),
        ),
        migrations.AlterField(
            model_name='ttlesson',
            name='curriculum_lesson_id',
            field=models.ForeignKey(db_column='curriculum_lesson_id', on_delete=django.db.models.deletion.PROTECT, to='polls.curriculumlesson'),
        ),
        migrations.AlterField(
            model_name='ttlesson',
            name='lessons_time_id',
            field=models.ForeignKey(db_column='lessons_time_id', on_delete=django.db.models.deletion.PROTECT, to='polls.lessontime'),
        ),
    ]
