# Generated by Django 4.2.6 on 2023-12-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_curriculum_discipline_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curriculumlesson',
            table='curriculum_lesson',
        ),
    ]
