# Generated by Django 4.2.6 on 2023-12-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_curriculumlesson_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumlesson',
            name='lesson_type',
            field=models.CharField(choices=[('PRA', 'Практика'), ('LEC', 'Лекция'), ('LAB', 'Лабораторная работа'), ('CRD', 'Зачет'), ('EXM', 'Экзамен')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ttlesson',
            name='day_name',
            field=models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT'), ('SUN', 'SUN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ttlesson',
            name='week_type',
            field=models.CharField(choices=[('EV', 'Четная неделя'), ('NE', 'Нечетная неделя'), ('CW', 'Зачетная неделя'), ('EX', 'Экзаменационная неделя')], max_length=2),
        ),
    ]
