# Generated by Django 4.2.6 on 2023-12-20 11:44

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='date_of_birth',
            field=models.DateField(validators=[polls.models.Tutor.validate_date]),
        ),
    ]
