# Generated by Django 5.0.3 on 2024-12-15 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_initial'),
        ('timetable', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('coefficient_id', models.AutoField(primary_key=True, serialize=False)),
                ('coef_num', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'coefficients',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('file', models.BinaryField()),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('final_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_type', models.CharField(choices=[('EXM', 'экзамен'), ('CRD', 'зачёт'), ('SEM1', '1 полусеместр'), ('SEM2', '2 полусеместр')], max_length=4)),
                ('scale_100', models.PositiveSmallIntegerField()),
                ('scale_5', models.PositiveSmallIntegerField()),
                ('scale_word', models.CharField(max_length=32)),
                ('scale_letter', models.CharField(max_length=1)),
                ('curriculum_id', models.ForeignKey(db_column='curriculum_id', on_delete=django.db.models.deletion.PROTECT, to='curriculum.curriculum')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='user.student')),
            ],
            options={
                'db_table': 'final_grades',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('scale_5', models.PositiveSmallIntegerField()),
                ('scale_word', models.CharField(max_length=32)),
                ('scale_100', models.PositiveSmallIntegerField()),
                ('scale_letter', models.CharField(max_length=1)),
                ('coefficient_id', models.ForeignKey(db_column='coefficient_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='progress.coefficient')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('hw_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2048)),
                ('hw_type', models.CharField(choices=[('IND', 'Индивидуальное'), ('GRP', 'Групповое')], max_length=3)),
                ('day_due', models.ForeignKey(db_column='day_due', on_delete=django.db.models.deletion.PROTECT, related_name='day_due', to='timetable.ttlesson')),
                ('day_given', models.ForeignKey(db_column='day_given', on_delete=django.db.models.deletion.PROTECT, related_name='day_given', to='timetable.ttlesson')),
                ('file_id', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='progress.file')),
                ('student_id', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.student')),
            ],
            options={
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(default=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='user.student')),
                ('tt_lesson_id', models.ForeignKey(db_column='tt_lesson_id', on_delete=django.db.models.deletion.PROTECT, to='timetable.ttlesson')),
            ],
            options={
                'db_table': 'students_attendances',
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_id', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.PROTECT, to='progress.grade')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, to='user.student')),
                ('tt_lesson_id', models.ForeignKey(db_column='tt_lesson_id', on_delete=django.db.models.deletion.PROTECT, to='timetable.ttlesson')),
            ],
            options={
                'db_table': 'students_progresses',
            },
        ),
        migrations.AddConstraint(
            model_name='finalgrade',
            constraint=models.CheckConstraint(check=models.Q(('scale_5__lte', 5)), name='progress_finalgrade_mark_scale_5_lte_5'),
        ),
        migrations.AddConstraint(
            model_name='finalgrade',
            constraint=models.CheckConstraint(check=models.Q(('scale_100__lte', 100)), name='progress_finalgrade_mark_scale_100_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='finalgrade',
            constraint=models.CheckConstraint(check=models.Q(('scale_word__in', ['отлично', 'хорошо', 'удовлетворительно', 'неудовлетворительно'])), name='progress_finalgrade_mark_scale_word_correct'),
        ),
        migrations.AddConstraint(
            model_name='finalgrade',
            constraint=models.CheckConstraint(check=models.Q(('scale_letter__in', ['A', 'B', 'C', 'D', 'E', 'F'])), name='progress_finalgrade_mark_scale_letter_correct'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(('scale_5__lte', 5)), name='progress_grade_mark_scale_5_lte_5'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(('scale_100__lte', 100)), name='progress_grade_mark_scale_100_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(('scale_word__in', ['отлично', 'хорошо', 'удовлетворительно', 'неудовлетворительно'])), name='progress_grade_mark_scale_word_correct'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(('scale_letter__in', ['A', 'B', 'C', 'D', 'E', 'F'])), name='progress_grade_mark_scale_letter_correct'),
        ),
    ]
