# Generated by Django 5.0.3 on 2024-12-16 12:36

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='scale_5',
            field=computed_property.fields.ComputedIntegerField(compute_from='calc_scale_5', editable=False),
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='scale_letter',
            field=computed_property.fields.ComputedCharField(compute_from='calc_scale_letter', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='scale_word',
            field=computed_property.fields.ComputedTextField(compute_from='calc_scale_word', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='grade',
            name='scale_5',
            field=computed_property.fields.ComputedIntegerField(compute_from='calc_scale_5', editable=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='scale_letter',
            field=computed_property.fields.ComputedCharField(compute_from='calc_scale_letter', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='scale_word',
            field=computed_property.fields.ComputedTextField(compute_from='calc_scale_word', editable=False, max_length=32),
        ),
    ]
